services:
  - name: iam
    url: http://localhost:3000
    # credentials:
    #   bearer:
    #     token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"

bundle:
  name: core_services.tar.gz
  prefix: static
  service: iam
  polling:
    min_delay_seconds: 5
    max_delay_seconds: 10
