version: '2'
services:
  opa-server:
    ports:
      - 3000:3000
    build: .
    depends_on:
      - db
    restart: always
    environment:
      SQL_DIALECT: mysql
      SQL_DSN: 'root:123@tcp(db:3306)/opadb?parseTime=true&charset=utf8'
      PORT: ':3000'
    command: ./opa-server
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: opadb
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
